### PR TITLE
Update BuildCraft-Pipes.zs

### PR DESCRIPTION
**Pull request by hanakocz**
Added Clay Pipe, oredicted glass input

### CODE REVIEW

**Comment by Dream-Master** [comment]
Why you not added it to https://github.com/Dream-Master/Mods-Get-Gregged because i updated it every day after satanicsanta gave it to me

**Comment by hanakocz** [comment]
Because I have no write access :P Just pull it into it :)

**Comment by Dream-Master** [comment]
Yes i know pull it in my acount because i updating it. I can updated it here too but i want to collecting all Scripts on one place. https://github.com/Dream-Master/Mods-Get-Gregged

**Comment by Dream-Master** [comment]
i add it manually to my github because its more up to date

**Comment by hanakocz** [comment]
Ok no prob. I need to update BC so i think there is more pipes....

**Comment by Dream-Master** [comment]
In the Future please make the pull Request on  https://github.com/Dream-Master/Mods-Get-Gregged
because this project are not up to date anymore. satanicsanta gave me the Project so i fork it to  https://github.com/Dream-Master/Mods-Get-Gregged and update it recently(every Day). On this Project no one working any more.

**Pull request merged**
